import type { Config } from 'tailwindcss';

// Tailwind v4 loads this file via `@config` in app/globals.css.
// Every value points at a token in src/styles/tokens.css — do not add raw hex here.
const v = (name: string) => `var(--fp-${name})`;

const tones = ['gray', 'blue', 'amber', 'green', 'red', 'violet', 'teal'] as const;
const stages = [
  'new',
  'qual',
  'docs',
  'banks',
  'submitted',
  'decision',
  'signing',
  'won',
  'lost',
] as const;

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: v('bg'),
        surface: {
          DEFAULT: v('surface'),
          subtle: v('surface-subtle'),
          muted: v('surface-muted'),
          sunken: v('surface-sunken'),
          track: v('surface-track'),
          skeleton: v('surface-skeleton'),
          hover: v('surface-hover'),
          'hover-task': v('surface-hover-task'),
          'hover-nav': v('surface-hover-nav'),
          'hover-menu': v('surface-hover-menu'),
          'active-nav': v('surface-active-nav'),
        },
        border: {
          DEFAULT: v('border'),
          strong: v('border-strong'),
          hover: v('border-hover'),
          subtle: v('border-subtle'),
          row: v('border-row'),
          'row-alt': v('border-row-alt'),
          'row-faint': v('border-row-faint'),
          'sidebar-footer': v('border-sidebar-footer'),
          timeline: v('border-timeline'),
          checkbox: v('border-checkbox'),
          dashed: v('border-dashed'),
          step: v('border-step'),
        },
        text: {
          DEFAULT: v('text'),
          secondary: v('text-secondary'),
          tertiary: v('text-tertiary'),
          muted: v('text-muted'),
          faint: v('text-faint'),
          disabled: v('text-disabled'),
          separator: v('text-separator'),
        },
        accent: {
          DEFAULT: v('accent'),
          hover: v('accent-hover'),
          strong: v('accent-strong'),
          soft: v('accent-soft'),
          softer: v('accent-softer'),
          ring: v('accent-ring'),
          'chip-hover': v('accent-chip-hover'),
          'border-soft': v('accent-border-soft'),
          disabled: v('accent-disabled'),
          'bar-muted': v('accent-bar-muted'),
        },
        success: {
          DEFAULT: v('success'),
          fg: v('success-fg'),
          bg: v('success-bg'),
          soft: v('success-soft'),
          softer: v('success-softer'),
          drop: v('success-drop'),
          border: v('success-border'),
        },
        warning: {
          DEFAULT: v('warning'),
          bg: v('warning-bg'),
          soft: v('warning-soft'),
          border: v('warning-border'),
          'border-strong': v('warning-border-strong'),
          text: v('warning-text'),
          icon: v('warning-icon'),
        },
        danger: {
          DEFAULT: v('danger'),
          bg: v('danger-bg'),
          dot: v('danger-dot'),
          soft: v('danger-soft'),
          softer: v('danger-softer'),
          row: v('danger-row'),
          drop: v('danger-drop'),
          border: v('danger-border'),
          'border-strong': v('danger-border-strong'),
          'border-stuck': v('danger-border-stuck'),
          'border-toggle': v('danger-border-toggle'),
          text: v('danger-text'),
          disabled: v('danger-disabled'),
          bar: v('danger-bar'),
        },
        tone: Object.fromEntries(
          tones.map((t) => [t, { bg: v(`tone-${t}-bg`), fg: v(`tone-${t}-fg`) }]),
        ),
        stage: Object.fromEntries(stages.map((s) => [s, v(`stage-${s}`)])),
        priority: { high: v('priority-high'), med: v('priority-med'), low: v('priority-low') },
        toast: {
          bg: v('toast-bg'),
          text: v('toast-text'),
          border: v('toast-border'),
          'icon-ok': v('toast-icon-ok'),
          'icon-block': v('toast-icon-block'),
          hover: v('toast-hover'),
        },
        overlay: v('overlay'),
      },
      fontFamily: {
        sans: [v('font-sans')],
        mono: [v('font-mono')],
        icon: [v('font-icon')],
      },
      fontSize: {
        'avatar-xs': v('text-avatar-xs'),
        'avatar-sm': v('text-avatar-sm'),
        'avatar-md': v('text-avatar-md'),
        tiny: v('text-tiny'),
        micro: v('text-micro'),
        caption: v('text-caption'),
        meta: v('text-meta'),
        sm: v('text-sm'),
        control: v('text-control'),
        base: [v('text-base'), { lineHeight: v('leading') }],
        logo: v('text-logo'),
        heading: v('text-heading'),
        stat: v('text-stat'),
        amount: v('text-amount'),
        title: [v('text-title'), { letterSpacing: v('tracking-title') }],
        kpi: [v('text-kpi'), { letterSpacing: v('tracking-kpi') }],
        display: [v('text-display'), { letterSpacing: v('tracking-kpi') }],
      },
      letterSpacing: {
        title: v('tracking-title'),
        kpi: v('tracking-kpi'),
        overline: v('tracking-overline'),
      },
      borderRadius: {
        bar: v('radius-bar'),
        track: v('radius-track'),
        badge: v('radius-badge'),
        'control-sm': v('radius-control-sm'),
        control: v('radius-control'),
        input: v('radius-input'),
        card: v('radius-card'),
        toast: v('radius-toast'),
        modal: v('radius-modal'),
        pill: v('radius-pill'),
      },
      spacing: {
        'fp-1': v('space-1'),
        'fp-2': v('space-2'),
        'fp-3': v('space-3'),
        'fp-4': v('space-4'),
        'fp-5': v('space-5'),
        'fp-6': v('space-6'),
        'fp-7': v('space-7'),
        'fp-8': v('space-8'),
        'fp-9': v('space-9'),
        'fp-10': v('space-10'),
        'fp-11': v('space-11'),
        'control-xs': v('control-xs'),
        'control-sm': v('control-sm'),
        'control-md': v('control-md'),
        control: v('control'),
        'control-lg': v('control-lg'),
        row: v('row-height'),
        'row-compact': v('row-height-compact'),
        'row-task': v('row-height-task'),
        'row-doc': v('row-height-doc'),
        'table-header': v('table-header-height'),
        'group-header': v('group-header-height'),
        sidebar: v('sidebar-width'),
        topbar: v('topbar-height'),
        aside: v('aside-width'),
        'kanban-col': v('kanban-col-min'),
        modal: v('modal-width'),
        'modal-lg': v('modal-width-lg'),
      },
      minWidth: { app: v('app-min-width') },
      maxWidth: { content: v('content-max') },
      boxShadow: {
        card: v('shadow-card'),
        'card-hover': v('shadow-card-hover'),
        segment: v('shadow-segment'),
        menu: v('shadow-menu'),
        toast: v('shadow-toast'),
        modal: v('shadow-modal'),
        focus: v('shadow-focus'),
        'focus-inset': v('shadow-focus-inset'),
        'focus-danger': v('shadow-focus-danger'),
      },
    },
  },
};

export default config;
